/* eslint-disable @next/next/no-sync-scripts */
'use client'

import SideBar from '@/components/sideBar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { createContext, useEffect } from 'react'
import ProviderCom from '@/redux/provider'

import { GoogleOAuthProvider } from '@react-oauth/google';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export const user: any = createContext(null)
export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  useEffect(() => {
    console.log(navigator.onLine);
    if (window != undefined) {
      require("../../node_modules/bootstrap/dist/js/bootstrap.esm")
    }

  }, [])


  return (
    <html lang="en">
      <head>

      </head>
      <body className={inter.className}>
        <GoogleOAuthProvider clientId='655514960292-ovts2qnt25johr0jm3tn5odjetaa0fvo.apps.googleusercontent.com'>
          <ProviderCom>

            <div className="globaldiv">

              <SideBar >
                {children}
              </SideBar>

            </div>
            <ToastContainer
              position="top-center"
              autoClose={3000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
            />
          </ProviderCom>
        </GoogleOAuthProvider>
      </body>

    </html >
  )
}
